version: "3.9"

services:
  dev:
    build:
    container_name: workspace-dev
    volumes:
      - ./:/workspace           
      - workspace_data:/workspace/data
    working_dir: /workspace
    tty: true
    stdin_open: true
    entrypoint: ["/usr/local/bin/clone.sh"]
    command: ["bash"]

volumes:
  workspace_data:
    driver: local
