version: "3.9"

services:
  dev:
    build:
    container_name: workspace-dev
    volumes:
      - ./:/workspace           
      - workspace_data:/workspace/data
    working_dir: /workspace
    tty: true
    stdin_open: true

volumes:
  workspace_data:
    driver: local
