version: "3.9"

services:
  dev:
    image: dev-stack:latest        # 👈 your base image
    container_name: workspace-dev
    volumes:
      - ./:/workspace              # mount WORKSPACE repo
      - workspace_data:/workspace/data
    working_dir: /workspace
    tty: true
    stdin_open: true

volumes:
  workspace_data:
    driver: local
